# Site settings
title: Zhou zhou's Blog 
author: zhouzhou
email: cctvzhouzhou@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal blog, most for computing tech.

baseurl: "/zhouzhoublog" # the subpath of your site, e.g. /blog
url: "https://cctvzhouzhou.github.io/zhouzhoublog/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cctvzhouzhou 
github_username: cctvzhouzhou
weixin_username: zhouzhou09030201

# Build settings
markdown: kramdown
# markdown: redcarpet
# redcarpet:
#        extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]


theme: jekyll-theme-hacker
